name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubunto-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'